language: android
jdk: oraclejdk8
notifications:
  email:
    - external-ci-notifications+braintree-android-drop-in@getbraintree.com
sudo: true
env:
  global:
    - TERM=dumb
android:
  components:
    - tools
    - tools
before_script:
  - echo y | android update sdk --no-ui --all --filter tools,platform-tools
  # Build three times, the first two builds will resolve dependencies via sdk-manager-plugin and then fail
  # https://github.com/JakeWharton/sdk-manager-plugin/issues/10
  - ./gradlew assembleDebug || true
  - ./gradlew assembleDebug || true
  - ./gradlew assembleDebug || true
script: ./gradlew --stacktrace --info lint test

